packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.2.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.0.0
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/carbon': ^1.2.7
  '@iconify-json/iconoir': ^1.2.7
  '@iconify-json/la': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/tabler': ^1.2.16
  '@iconify-json/teenyicons': ^1.2.2
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/uim': ^1.2.3
  '@iconify-json/vscode-icons': ^1.2.14
  '@iconify/json': ^2.2.307
  '@shikijs/vitepress-twoslash': ^2.3.2
  '@types/node': ^22.13.4
  '@unocss/reset': ^65.5.0
  '@vueuse/core': ^12.7.0
  bumpp: ^10.0.3
  eslint: ^9.20.1
  floating-vue: ^5.2.2
  lint-staged: ^15.4.3
  pinia: ^3.0.1
  pnpm: ^10.4.0
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.1
  unocss: ^65.5.0
  unplugin-vue-components: ^28.1.0
  vite: ^6.1.0
  vite-tsconfig-paths: ^5.1.4
  vitepress: ^2.0.0-alpha.2
  vitepress-plugin-group-icons: ^1.3.5
  vitest: ^3.0.5
  vue: ^3.5.13
